# Site settings ...
uri: amanas.github.io
url: https://amanas.github.io
name: Andrés Mañas
title: amanas blog a notes 
email: andresmanasmanas@gmail.com
author: amanas
baseurl: ""
keywords: "Maths, Data, Algorithms"
description: "A place to share thoughts (and mistakes)"
social_username: amanas

# Build settings ...
sass:
  style: compressed
markdown: kramdown
encoding: "utf-8"
paginate: 5
permalink: /post/:title
paginate_path: "/page/:num/"

# Plugins ...
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
