# Site settings ...
uri:             amanas.github.io
url:             https://amanas.github.io
name:            Andrés Mañas
title:           Andrés Mañas home site
email:
author:          amanas
baseurl:         ""
keywords:        "Andrés Mañas Home Site amanas Maths Data Algorithms"
description:     "Andrés Mañas home site. A place with notes, thoughts and mistakes about data, maths and algorithms"
social_username: amanas

# Build settings ...
sass:
  style:         compressed
markdown:        kramdown
encoding:        "utf-8"
paginate:        10
permalink:       /:title
paginate_path:   "/page/:num/"
highlighter:     rouge
permalink:       pretty



# Plugins ...
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-compose
